version: '{build}'
os: Visual Studio 2015
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: 1zB4tgv4S6lc2uhETUrTprrBCW8tVUib/ny3wI8tudjWyhFkJz9yKw45Vyc7lJ9L
install:
- ps: >-
    nuget update -self

    Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"

    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"

    & .\dotnet-install.ps1 -Channel "preview" -Version "1.0.0-preview2-003121" -InstallDir "$env:DOTNET_INSTALL_DIR"

build: off
test_script:
- ps: dotnet restore
- ps: ./Coverage.ps1
